######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 24 13:47:12 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . /opt/X11/include/X11 /usr/include/malloc /opt/local/include
CONFIG += qt
LIBS += -L. -lrevel -lxvidcore -lX11 -L/opt/X11/lib -L/opt/local/lib


# Input
HEADERS += CImg.h lambda.h revel.h
SOURCES += lambda.cpp main.cpp
